### ISSUE TITLE
Patrick's MP3 Stuff

### ISSUE THREAD

**Issue by pjdeavers** [cyinwei/guessingGame#1]
Here's the most current stuff I had for MP3. My partner did a pretty good job with the server. https://github.com/pjdeavers/ECEN-424-Final-Project.git

**Comment by pjdeavers** [comment]
I'm just going to copy paste some of this stuff into the framework of what we have. The telnet client should work fine now.

**Comment by cyinwei** [comment]
okay good, are we gonna use your repo or mine?

**Comment by cyinwei** [comment]
hey I added you as a collab, just push to it when you're done

**Comment by cyinwei** [comment]
working on it after lunch

**Comment by pjdeavers** [comment]
We should use yours. What I uploaded is super easy to copt paste from

Sent from my T-Mobile 4G LTE Device

-------- Original message --------

**Comment by cyinwei** [comment]
okay, im working on the server now.  Using your server as a base

**Comment by cyinwei** [comment]
okay, alejandro's server is great.  We can use (all) of it, and add the lobby functionality later with some synchronized/locked messages

**Comment by pjdeavers** [comment]
Cool. I got class til 3:35 but I'm gonna work on it after. Want to meet up later? 

Sent from my T-Mobile 4G LTE Device

-------- Original message --------

**Comment by cyinwei** [comment]
hey, some other work came up, i'm busy right now until like 9ish.  i'll update what I have so far.  I'm stuck on the server, where we have to broadcast a message into all the connected people.

**Comment by cyinwei** [comment]
Hey good work today +1
